// <auto-generated />
namespace rector_blog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class editNameColumnBlogCategoryTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editNameColumnBlogCategoryTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202012091545274_editNameColumnBlogCategoryTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
